version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres
    volumes:
      - ./psqldata:/var/lib/postgresql/data
    ports:
        - "5432:5432"